### ISSUE TITLE
Investigate colour indexes

### ISSUE THREAD

**Issue by RichardBrown384** [RichardBrown384/riscos-artworks-js#118]
# About

`DACHSHUND,d94`'s reflection gets rendered as solid black when it should look like the original figure.

The reflection's linear gradients where found to have `stop-colors='none'`.

The colour indexes used to generate these gradients where found to have bit-29 set

# Task

- [x] Investigate the available files to find which ones have "unusual" colours
- [x] Identify any patterns
- [x] Make changes to the code so the colours are interpreted correctly
- [x] Update the README

**Comment by RichardBrown384** [comment]
The following files have unusual colours defined

```
AABOX,d94
AQUARIUS,d94
ARCHIMEDIA,d94
ARROWS,d94
BALLOON2,d94
BEETLE,d94
BILLY,d94
BOY,d94
BROKNROPE,d94
BULLEIDPAC,d94
BUTTERFLY2,d94
CASH,d94
CASSETTE2,d94
CATCOV8,d94
CATS2,d94
CITY,d94
CLOWN,d94
COLDEMO,d94
COMPOSE1,d94
CORSAGE,d94
CROFT,d94
DACHSHUND,d94
DEATHGLORY,d94
DRAGONI,d94
EGGNERGY,d94
ENCOUNT,d94
ENTRY,d94
FASTENERS,d94
FIRE2,d94
FIREBIRD2,d94
HINDSDESN,d94
JOBSEARCH,d94
KARAF2,d94
KINGFISHER,d94
KITCHEN4,d94
KUWAIT,d94
MACHINE,d94
MINIGR,d94
MONITOR2,d94
MYLOGO,d94
NO1,d94
PERIWINKLE,d94
POPPY,d94
POPPYGRP,d94
POPPYRAY,d94
POTPLANT,d94
PUSSY,d94
RACBOX,d94
RADIOACT2,d94
RAT,d94
ROSE,d94
ROSE3,d94
ROSE4,d94
SCREW,d94
SGAUGE,d94
SHADOWS,d94
SHUTTLE1,d94
SPIRAL,d94
SPOTLIGHT,d94
STAMP2,d94
STCUTHBERT,d94
SUNSET3,d94
TAXDISC1,d94
TOON,d94
TORNADO,d94
TRIKE,d94
UNDEAD,d94
VCR,d94
VENMASK1,d94
VENMASK2,d94
VR6,d94
WAJANG2,d94
WINDOWCAT,d94
WORLD,d94
```
