### ISSUE TITLE
Geometry interpolation/blending - bezier splits

### ISSUE THREAD

**Issue by RichardBrown384** [RichardBrown384/riscos-artworks-js#165]
# About

Current geometry experiments involving paths with differing number of points have all used line segments.

Contributes to #116 

# Task

Write example files that require a bezier split and examine the behaviour

# AC

- [x] Investigate if Bezier curves are indeed split ✅ 
- [x] Determine if !AWViewer splits a Bezier segment more than once. This is interesting because of the potential accumulation of rounding errors implied by doing multiple splits with say de Casteljau ✅ 
- [x] If necessary, extend code to split bezier sections by parametric distance/weights CF de Casteljau's algorithm ✅ 
- [x] Produce examples of bezier split blends
