### ISSUE TITLE
Blends: arc lengths and point correspondences

### ISSUE THREAD

**Issue by RichardBrown384** [RichardBrown384/riscos-artworks-js#189]
# About

From the evidence accrued for #116 to date it appears that !AWViewer comes up with a correspondence
between the points on the source and target paths. That is to say, points on the source are mapped onto
points and segments of the target and points on the target are mapped onto points and segments of the source.

Once it has this correspondence the evidence suggests it then uses arc length ratios to position the inserted points.

It would be useful to have a data structure that represents the point correspondence that can then be used to
tell our simulated blend routines how to treat the geometry prior to blending by doing the insertions automatically.
Up until now, we've been computing the arc lengths and insertion positions by hand.

In order to do this we're going to need routines to calculate the arc lengths of straight lines and Béziers.

# Tasks

- [ ] Add routines to compute arc lengths of straight lines and Béziers
- [ ] Devise data structure to represent the correspondence
- [ ] Add a routine, that given the source, target and correspondence, computes the insertions point weights.
This is a design choice. We can then feed the weights into the existing insertion routines we have and
not couple things together too tightly.

# Useful sites

https://raphlinus.github.io/curves/2018/12/28/bezier-arclength.html
https://github.com/Pomax/bezierjs

# Caveats

This issue is based on some assumptions about what we suspect !AWViewer is doing. It's possible that there 
may be hitherto unexplored cases that invalidate the entire idea.
